services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    hostname: contMysql
    restart: always
    networks:
      - network1
    environment:
      - MYSQL_ROOT_PASSWORD=senhaForte
      - MYSQL_DATABASE=nowe
    ports:
      - 3307:3306

  apiweon:
    build: ./
    container_name: apiweon
    volumes:
      - .:/home/api
    ports:
      - 3300:3300
    command: npm run dev
    depends_on:
      - mysqldb
    restart: always
    networks:
      - network1

networks:
  network1:
    name: "ApiWeon"
    external: true

