version: '3'
services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    hostname: contMysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    env_file:
      - .env
    ports:
      - "${DB_MYSQL_PORT}:3306"
    networks:
      - mynetwork

  apiweon:
    build: ./
    container_name: apiweon
    volumes:
      - .:/home/api
    ports:
      - "${API_PORT}:3300"
    env_file:
      - .env
    command: npm start
    depends_on:
      - mysqldb
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
