version: '3'
services:
  apiweon:
    build: ./
    container_name: "${DOCKER_CONTAINER_NAME}"
    volumes:
      - ./:/home/api/
    ports:
      - "${API_PORT}:3300"
    env_file:
      - .env
    command: npm start
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
