version: '3'
services:
  apiweon:
    build: ./
    container_name: "${DOCKER_CONTAINER_NAME}"
    volumes:
      - ./dist:/home/api/dist
    ports:
      - "${API_PORT}:3300"
    env_file:
      - .env
    command: npm start
    #depends_on:
      #- mysqldb
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
